/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package onlineexaminationsystem;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author Programmer
 */
public class AddQues extends javax.swing.JFrame {

    String course;
    private Statement st;
    /**
     * Creates new form AddViewDelCourse
     */
    public AddQues(String course) {
        initComponents();
        this.course=course;
        cours.setText(course);
        db();
    }

   private void db(){
       try{
           Class.forName("sun.jdbc.odbc.JdbcOdbcDriver");
            System.out.println("DriverLoaded");
            String url = "jdbc:odbc:CourseDSN";
            Connection con = DriverManager.getConnection(url);

            System.out.println("Connection Established Successfully");
            
             st=con.createStatement();
            
       }catch(Exception e){
           
       }
   }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        NqStatement = new javax.swing.JTextArea();
        op1 = new javax.swing.JTextField();
        op2 = new javax.swing.JTextField();
        op4 = new javax.swing.JTextField();
        op3 = new javax.swing.JTextField();
        correctop = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        NqID = new javax.swing.JTextField();
        btnSave = new java.awt.Button();
        cours = new javax.swing.JLabel();
        btnback = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        NqStatement.setColumns(20);
        NqStatement.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
        NqStatement.setRows(5);
        jScrollPane1.setViewportView(NqStatement);

        op1.setBackground(new java.awt.Color(240, 240, 240));
        op1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N

        op2.setBackground(new java.awt.Color(240, 240, 240));
        op2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N

        op4.setBackground(new java.awt.Color(240, 240, 240));
        op4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N

        op3.setBackground(new java.awt.Color(240, 240, 240));
        op3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N

        correctop.setBackground(new java.awt.Color(240, 240, 240));
        correctop.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel1.setText("Option 1");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setText("Option 2");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setText("Option 3");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel4.setText("Option 4");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel5.setText("Correct Option");

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel6.setText("Question #");

        NqID.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        NqID.setText("0");

        btnSave.setFont(new java.awt.Font("Vivaldi", 3, 24)); // NOI18N
        btnSave.setLabel("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        cours.setFont(new java.awt.Font("Vivaldi", 3, 36)); // NOI18N
        cours.setText("Course");

        btnback.setFont(new java.awt.Font("Vivaldi", 3, 18)); // NOI18N
        btnback.setText("back");
        btnback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(btnback, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cours)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(op4, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(op3, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(op2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(op1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(correctop, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 804, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(NqID, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cours)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(NqID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(op1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(op2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(op3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(op4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(correctop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(btnback)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
                            String ID=NqID.getText();
                            String Q_Stmt = NqStatement.getText();
                            String op_1 = op1.getText();
                            String op_2 = op2.getText();
                            String op_3 = op3.getText();
                            String op_4 = op4.getText();
                            String correct_op = correctop.getText();
                             
         
                    try{
                        
                                 
            
            if(course=="C++"){
                String query = "INSERT INTO Cpp VALUES('"+ID+"','"+Q_Stmt+"','"+op_1+"','"+op_2+"','"+op_3+"','"+op_4+"','"+correct_op+"')";
                st.executeUpdate(query);
                System.out.println("all ok");
                
                if(ID=="10"){
                JOptionPane.showMessageDialog(null,"All question is saved");
                new ManageCourse().setVisible(true);
                dispose();
            }
            }
            if(course=="JAVA"){
                String query = "INSERT INTO JAVA VALUES('"+ID+"','"+Q_Stmt+"','"+op_1+"','"+op_2+"','"+op_3+"','"+op_4+"','"+correct_op+"')";
                st.executeUpdate(query);
                if(ID=="10"){
                JOptionPane.showMessageDialog(null,"All question is saved");
                new ManageCourse().setVisible(true);
                dispose();
            }
            }
            if(course=="C#"){
               String query = "INSERT INTO CSharp VALUES('"+ID+"','"+Q_Stmt+"','"+op_1+"','"+op_2+"','"+op_3+"','"+op_4+"','"+correct_op+"')";
                st.executeUpdate(query);
                if(ID=="10"){
                JOptionPane.showMessageDialog(null,"All question is saved");
                new ManageCourse().setVisible(true);
                dispose();
            }
            }
            
           if(course=="PYTHON"){
               String query = "INSERT INTO PYTHON VALUES('"+ID+"','"+Q_Stmt+"','"+op_1+"','"+op_2+"','"+op_3+"','"+op_4+"','"+correct_op+"')";
                st.executeUpdate(query);
                if(ID=="10"){
                JOptionPane.showMessageDialog(null,"All question is saved");
                new ManageCourse().setVisible(true);
                dispose();
            }
           }
           JOptionPane.showMessageDialog(null,"Question is add");
            
            clearText();
            
           }
                            catch(Exception ae)
                            {
                                System.out.println(ae);
                            }
                              
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSaveActionPerformed

    private void clearText(){
        NqStatement.setText("");
        op1.setText("");
        op2.setText("");
        op3.setText("");
        op4.setText("");
        correctop.setText("");
    }
    
    private void btnbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbackActionPerformed
        dispose();
        new ManageCourse().setVisible(true);
    }//GEN-LAST:event_btnbackActionPerformed

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField NqID;
    private javax.swing.JTextArea NqStatement;
    private java.awt.Button btnSave;
    private javax.swing.JButton btnback;
    private javax.swing.JTextField correctop;
    private javax.swing.JLabel cours;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField op1;
    private javax.swing.JTextField op2;
    private javax.swing.JTextField op3;
    private javax.swing.JTextField op4;
    // End of variables declaration//GEN-END:variables
}
