/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package onlineexaminationsystem;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author Programmer
 */
public class ForgetPassword extends javax.swing.JFrame {

    private String txt;
    private String hobby;
    private Statement st;
    /**
     * Creates new form ForgetPassword
     */
    public ForgetPassword() {
        initComponents();
        
        btnNext2.hide();        // Hide button next
        
        btnUpdt.hide();     // hide button Update
        
        db();       // call database method
               
    }       // end of constructior
    
    private void db(){          // create database connection
        try{
            Class.forName("sun.jdbc.odbc.JdbcOdbcDriver");
            String database ="Studen_InfoDB.mdb";
            String url = "jdbc:odbc:StudentInfoDSN";
             Connection con = DriverManager.getConnection(url); 

             st=con.createStatement();
             
        }catch(Exception e){
            
        }
    }       // end of database method
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lbl = new javax.swing.JLabel();
        txtUser = new javax.swing.JTextField();
        btnNext = new javax.swing.JButton();
        btnNext2 = new javax.swing.JButton();
        lblback = new javax.swing.JButton();
        btnUpdt = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        jLabel1.setText("Forget Password");

        lbl.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        lbl.setText("User Name");

        txtUser.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        btnNext.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        btnNext.setText("Next");
        btnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextActionPerformed(evt);
            }
        });

        btnNext2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        btnNext2.setText("Next");
        btnNext2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNext2ActionPerformed(evt);
            }
        });

        lblback.setFont(new java.awt.Font("Tiger Expert", 3, 24)); // NOI18N
        lblback.setText("back");
        lblback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lblbackActionPerformed(evt);
            }
        });

        btnUpdt.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        btnUpdt.setText("Update");
        btnUpdt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdtActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(233, 233, 233)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(262, 262, 262))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbl)
                                .addGap(18, 18, 18)
                                .addComponent(txtUser, javax.swing.GroupLayout.DEFAULT_SIZE, 392, Short.MAX_VALUE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(btnUpdt, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnNext2, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnNext, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(133, 133, 133))))
            .addGroup(layout.createSequentialGroup()
                .addGap(142, 142, 142)
                .addComponent(lblback, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jLabel1)
                .addGap(98, 98, 98)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl)
                    .addComponent(txtUser, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(52, 52, 52)
                .addComponent(btnNext2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnNext)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnUpdt)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addComponent(lblback)
                .addGap(55, 55, 55))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed

        txt=txtUser.getText();
        try{
                    
                    
              String query = "SELECT * FROM studenttbl where user_name='"+txt+"'";

                
                 ResultSet rs =  st.executeQuery(query);
            if(rs.next()){                
                     hobby = rs.getString("Hoby");  
                     lbl.setText("Your hobby");
                         btnNext.hide();
                         btnNext2.show();
                                         txtUser.setText("");

                 } 
            else{
     
                          JOptionPane.showMessageDialog(null,"You have not registered user ");    

 }
                 
                           
                }catch(Exception ae)
                {
                    System.out.println(ae);
                }    }//GEN-LAST:event_btnNextActionPerformed

    private void btnNext2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNext2ActionPerformed
        String txt2= txtUser.getText();
        if(txt2.equals(hobby)){
                btnNext2.hide();
                txtUser.setText("");
                lbl.setText("Enter New Password");
                btnUpdt.show();
                
        }
        else{
            JOptionPane.showMessageDialog(null,"Hobby doesn't is Matched ");
        }
    }//GEN-LAST:event_btnNext2ActionPerformed

    private void lblbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lblbackActionPerformed

        dispose();
        new LoginChoice().setVisible(true);
    }//GEN-LAST:event_lblbackActionPerformed

    private void btnUpdtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdtActionPerformed
 
        String txt3=txtUser.getText();
        try{           
            
            
            String query = "UPDATE studenttbl SET password='"+txt3+"' WHERE user_name='"+txt+"'";
            System.out.println("Row is Updated");
                 st.executeUpdate(query);
                 
                 JOptionPane.showMessageDialog(null,"Password Changed Successfully!");
                 
            
       }
        catch(Exception ae)
        {
        
                                 System.out.println(ae);

        }           // TODO add your handling code here:
    }//GEN-LAST:event_btnUpdtActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnNext;
    private javax.swing.JButton btnNext2;
    private javax.swing.JButton btnUpdt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lbl;
    private javax.swing.JButton lblback;
    private javax.swing.JTextField txtUser;
    // End of variables declaration//GEN-END:variables
}
