/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package onlineexaminationsystem;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author Programmer
 */
public class LoginChoice extends javax.swing.JFrame {

    private Statement st;
    /**
     * Creates new form LoginChoice
     */
    String username;
    String password;
    
    public LoginChoice() {
        
        initComponents();
         btnForgetPass.hide();
        btnRegist.hide();
        db();
    }

    
    private void db(){  
        try{
            Class.forName("sun.jdbc.odbc.JdbcOdbcDriver");
            String database ="Studen_InfoDB.mdb";
            String url = "jdbc:odbc:StudentInfoDSN";
                        System.out.println("ok0");

             Connection con = DriverManager.getConnection(url); 
                        System.out.println("ok");

             st=con.createStatement();
            
        }catch(Exception e){
            System.out.println(e);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        combo = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txt = new javax.swing.JTextField();
        pass = new javax.swing.JPasswordField();
        btnlogin = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        btnRegist = new javax.swing.JToggleButton();
        jLabel4 = new javax.swing.JLabel();
        HideShowPass = new javax.swing.JCheckBox();
        btnForgetPass = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 204, 204));
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Vivaldi", 3, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Examination System");

        combo.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        combo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Admin", "User" }));
        combo.setSelectedIndex(-1);
        combo.setToolTipText("");
        combo.setName(""); // NOI18N
        combo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setText("User Name");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel3.setText("Password");

        txt.setBackground(new java.awt.Color(240, 240, 240));
        txt.setBorder(null);

        pass.setBackground(new java.awt.Color(240, 240, 240));
        pass.setBorder(null);
        pass.setEchoChar('*');
        pass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passActionPerformed(evt);
            }
        });

        btnlogin.setFont(new java.awt.Font("Tiger Expert", 3, 24)); // NOI18N
        btnlogin.setText("Login");
        btnlogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnloginActionPerformed(evt);
            }
        });

        btnRegist.setText("SignUp");
        btnRegist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Times New Roman", 2, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 0, 51));
        jLabel4.setText("Select Type");

        HideShowPass.setToolTipText("Hide/show");
        HideShowPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HideShowPassActionPerformed(evt);
            }
        });

        btnForgetPass.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btnForgetPass.setText("ForgetPassword?");
        btnForgetPass.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnForgetPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnForgetPassActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(26, 273, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 436, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(223, 223, 223))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(204, 204, 204)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnlogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel2)
                                            .addComponent(jLabel3))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txt)
                                            .addComponent(pass)
                                            .addComponent(jSeparator1)
                                            .addComponent(jSeparator2))))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(combo, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addComponent(jLabel4)
                                            .addGap(30, 30, 30)))
                                    .addComponent(HideShowPass)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btnForgetPass, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(72, 72, 72)))
                        .addGap(78, 78, 78))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnRegist, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jLabel1)
                .addGap(32, 32, 32)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(combo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(pass, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(5, 5, 5)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 3, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(HideShowPass))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRegist)
                    .addComponent(btnForgetPass, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addComponent(btnlogin, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(117, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void comboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboActionPerformed
            if(combo.getSelectedItem()=="Admin"){
                
            jLabel1.setText("Admin");
            btnRegist.hide();
            btnForgetPass.hide();
            
        }
        if(combo.getSelectedItem()=="User"){
            
             jLabel1.setText("User");
             btnRegist.show();
            btnForgetPass.show();
        }
    }//GEN-LAST:event_comboActionPerformed

    private void passActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passActionPerformed
    }//GEN-LAST:event_passActionPerformed

         
    private void btnloginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnloginActionPerformed

        if(combo.getSelectedItem()==null){
            JOptionPane.showMessageDialog(null,"Select Type");
            
        }
        if(combo.getSelectedItem()=="Admin"){
            admin();
            
        }
        if(combo.getSelectedItem()=="User"){
            
            user();
        }
        
    }//GEN-LAST:event_btnloginActionPerformed

    private void btnRegistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistActionPerformed
            
            dispose();
            new SignUp().setVisible(true);
    }//GEN-LAST:event_btnRegistActionPerformed

    private void HideShowPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HideShowPassActionPerformed
        if (HideShowPass.isSelected()) {
            pass.setEchoChar((char)0); //password = JPasswordField
        } else {
            pass.setEchoChar('*');
        }
    }//GEN-LAST:event_HideShowPassActionPerformed

    private void btnForgetPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnForgetPassActionPerformed
        
         dispose();
         new ForgetPassword().setVisible(true);
    }//GEN-LAST:event_btnForgetPassActionPerformed
        // end of Action Listener 
          
    private void admin(){       // create admin method
         username= txt.getText();
         password=pass.getText();
          try{
            
              String query = "SELECT * FROM admin where admin='"+username+"' and Password='"+password+"'";

                
                 ResultSet rs =  st.executeQuery(query);

                 if(!rs.next())
                 {
                     JOptionPane.showMessageDialog(null,"Incorrect UserName or password");
                     
                     
                 }
                 else
                 {
                                            dispose();
                                            new AdminPanel().setVisible(true);
                                         JOptionPane.showMessageDialog(null,"Login Successfull");

                 }
        }
        catch(Exception ae)
        {
            JOptionPane.showMessageDialog(null,"Invalid login or Password");
            System.out.println(ae);
        }
    }       // end of admin method
    
    
    private void user(){
        username= txt.getText();
         password=pass.getText();
            try{
            
              String query = "SELECT * FROM studenttbl where user_name='"+username+"' and password='"+password+"'";

                
                 ResultSet rs =  st.executeQuery(query);

                 if(!rs.next())
                 {
                     JOptionPane.showMessageDialog(null,"Incorrect UserName or password");
                 }
                 else
                 {
                                            dispose();
                                        new UserPanel(username).setVisible(true);
                                         JOptionPane.showMessageDialog(null,"Login Successfull");

                 }

                
                
            }
            catch(Exception ae)
            {
                                 System.out.println( ae);


            }
    }
       
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox HideShowPass;
    private javax.swing.JButton btnForgetPass;
    private javax.swing.JToggleButton btnRegist;
    private javax.swing.JButton btnlogin;
    private javax.swing.JComboBox combo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JPasswordField pass;
    private javax.swing.JTextField txt;
    // End of variables declaration//GEN-END:variables
}
