/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package onlineexaminationsystem;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author Programmer
 */
public class StartTest extends javax.swing.JFrame implements ActionListener {

    String Course, username,op5, query;
    int i=1;
   static int count=0;
    private Statement st;
    /**
     * Creates new form StartTest
     */
    public StartTest(String Course, String username) {
        initComponents();
        
        this.Course=Course;
        this.username=username;
        course.setText(Course);
        ButtonGrop();
        db();
          set(i);
    }
    
    private void ButtonGrop(){
        rd1.addActionListener(this);
        rd2.addActionListener(this);
        rd3.addActionListener(this);
        rd4.addActionListener(this);

        BG.add(rd1);
        BG.add(rd2);
        BG.add(rd3);
        BG.add(rd4);
        
    }
    private void db(){
        try{
            Class.forName("sun.jdbc.odbc.JdbcOdbcDriver");
                   System.out.println("DriverLoaded");
            String url = "jdbc:odbc:CourseDSN";
            Connection con = DriverManager.getConnection(url);

            System.out.println("Connection Established Successfully");
            
             st=con.createStatement();
        }catch(Exception e){
            
        }
    }
     private  void set( int c)
    {
        UnSelecRadioButton();
        no.setText(Integer.toString(c));
        int ID = c;
        
            if(Course=="C++"){
                
             query ="SELECT * FROM Cpp where ID ='"+ID+"' ";
             setQuestions();
             
            }
            if(Course=="JAVA"){
                
             query ="SELECT * FROM  JAVA where ID ='"+ID+"' ";
           setQuestions();
            
            }
            if(Course=="C#"){
                
             query ="SELECT * FROM CSharp where ID ='"+ID+"' ";
            setQuestions();
            
            }
            if(Course=="PYTHON"){
                
             query ="SELECT * FROM PYTHON where ID ='"+ID+"' ";
            setQuestions();            
            
            }
              
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BG = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        NqStatement = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        rd1 = new javax.swing.JRadioButton();
        rd3 = new javax.swing.JRadioButton();
        rd4 = new javax.swing.JRadioButton();
        course = new javax.swing.JLabel();
        rd2 = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        q1 = new javax.swing.JLabel();
        no = new javax.swing.JLabel();
        q = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        NqStatement.setEditable(false);
        NqStatement.setColumns(20);
        NqStatement.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
        NqStatement.setRows(5);
        jScrollPane1.setViewportView(NqStatement);

        jLabel1.setFont(new java.awt.Font("Tiger Expert", 3, 24)); // NOI18N
        jLabel1.setText("Question:");

        rd1.setText("jRadioButton1");

        rd3.setText("jRadioButton2");

        rd4.setText("jRadioButton3");

        course.setFont(new java.awt.Font("Tiger Expert", 3, 36)); // NOI18N
        course.setText("Course");

        rd2.setText("jRadioButton1");

        jButton1.setFont(new java.awt.Font("Vivaldi", 3, 18)); // NOI18N
        jButton1.setText("Next");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        q1.setFont(new java.awt.Font("Tiger Expert", 3, 24)); // NOI18N
        q1.setText("= 10");

        no.setFont(new java.awt.Font("Vivaldi", 3, 24)); // NOI18N
        no.setText("No");

        q.setFont(new java.awt.Font("Tiger Expert", 3, 24)); // NOI18N
        q.setText("Total Questions");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rd1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(no))
                            .addComponent(course))
                        .addGap(405, 414, Short.MAX_VALUE)
                        .addComponent(q)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(q1)
                        .addGap(19, 19, 19))
                    .addComponent(rd2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(rd3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(rd4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addComponent(jScrollPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(course)
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(no)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(q)
                        .addComponent(q1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addComponent(rd1)
                .addGap(18, 18, 18)
                .addComponent(rd2)
                .addGap(18, 18, 18)
                .addComponent(rd3)
                .addGap(18, 18, 18)
                .addComponent(rd4)
                .addGap(18, 18, 18)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        
        i+=1;
        if(i==11){
            JOptionPane.showMessageDialog(null,"Test Completed\nShowResult");
            dispose();
            new ResultCard(Course, username,count).setVisible(true);
        }
        set(i);
    }//GEN-LAST:event_jButton1ActionPerformed

   public void actionPerformed(ActionEvent e){
        
        if(e.getActionCommand().equals(op5))
            {
           count =count+1;
           System.out.println(count);
            }
        else{
       System.out.println("not correct");
   }
    }
    
    private void setQuestions(){
       try{ 
           ResultSet rs = st.executeQuery(query);
            
            while(rs.next())
            {
              String Stmt = rs.getString("Q_Stmt");
              NqStatement.setText(Stmt);
                 String op1 = rs.getString("op_1");
                rd1.setText(op1);
               
                  String op2 = rs.getString("op_2");
                                   rd2.setText(op2);

                  String op3 = rs.getString("op_3");
                                   rd3.setText(op3);

                  String op4 = rs.getString("op_4");
                                   rd4.setText(op4);

                   op5 = rs.getString("correct_op");
            }   
            }
       catch (Exception e){
           
       }
    }
    
private void UnSelecRadioButton(){
    BG.clearSelection();
  
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup BG;
    private javax.swing.JTextArea NqStatement;
    private javax.swing.JLabel course;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel no;
    private javax.swing.JLabel q;
    private javax.swing.JLabel q1;
    private javax.swing.JRadioButton rd1;
    private javax.swing.JRadioButton rd2;
    private javax.swing.JRadioButton rd3;
    private javax.swing.JRadioButton rd4;
    // End of variables declaration//GEN-END:variables
}
