/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package onlineexaminationsystem;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author Programmer
 */
public class ViewDelQues extends javax.swing.JFrame {
 int i=1;
    String course;
    private Statement st;
    private String query;
    /**
     * Creates new form ViewDelQues
     */
    public ViewDelQues(String course) {
        initComponents();
        this.course=course;
        cours.setText(course);
        db();
        
        view(i);
    }
    
    private void db(){
        try{
            Class.forName("sun.jdbc.odbc.JdbcOdbcDriver");
            String url = "jdbc:odbc:CourseDSN";
             Connection con = DriverManager.getConnection(url); 

             st=con.createStatement();
        }catch(Exception e){
            
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        btndel = new java.awt.Button();
        jLabel3 = new javax.swing.JLabel();
        cours = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        No3 = new javax.swing.JTextField();
        correctOption = new javax.swing.JTextField();
        No2 = new javax.swing.JTextField();
        No4 = new javax.swing.JTextField();
        NqID = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        No1 = new javax.swing.JTextField();
        btnback = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        NqStatement = new javax.swing.JTextArea();
        btnnext = new java.awt.Button();
        btnprev = new java.awt.Button();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel5.setText("Correct Option");

        btndel.setFont(new java.awt.Font("Tiger Expert", 3, 24)); // NOI18N
        btndel.setLabel("Delete");
        btndel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndelActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setText("Option 3");

        cours.setFont(new java.awt.Font("Tiger Expert", 3, 36)); // NOI18N
        cours.setText("Course");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel4.setText("Option 4");

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel1.setText("Option 1");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setText("Option 2");

        No3.setEditable(false);
        No3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N

        correctOption.setEditable(false);
        correctOption.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N

        No2.setEditable(false);
        No2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N

        No4.setEditable(false);
        No4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N

        NqID.setEditable(false);
        NqID.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        NqID.setText("0");

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel6.setText("Question #");

        No1.setEditable(false);
        No1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N

        btnback.setFont(new java.awt.Font("Vivaldi", 3, 18)); // NOI18N
        btnback.setText("back");
        btnback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbackActionPerformed(evt);
            }
        });

        NqStatement.setEditable(false);
        NqStatement.setColumns(20);
        NqStatement.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
        NqStatement.setRows(5);
        jScrollPane1.setViewportView(NqStatement);

        btnnext.setFont(new java.awt.Font("Tiger Expert", 3, 24)); // NOI18N
        btnnext.setLabel("Next");
        btnnext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnnextActionPerformed(evt);
            }
        });

        btnprev.setFont(new java.awt.Font("Tiger Expert", 3, 24)); // NOI18N
        btnprev.setLabel("prev");
        btnprev.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnprevActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(btnback, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnprev, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnnext, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cours)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btndel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(No4, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(No3, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(No2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(No1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(correctOption, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 804, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(NqID, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cours)
                    .addComponent(btndel, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(NqID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(No1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(No2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(No3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(No4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(correctOption, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnprev, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnback)
                    .addComponent(btnnext, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btndelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndelActionPerformed

        try{
                    System.out.println("DriverLoaded");
            
            
            if(course=="C++"){
            String delquery ="DELETE  FROM Cpp where ID ='"+i+"' ";
            st.executeUpdate(delquery);
            
            JOptionPane.showMessageDialog(null,"Question is removed");
               }
               
            if(course=="JAVA"){
            String delquery ="DELETE  FROM JAVA where ID ='"+i+"' ";
            st.executeUpdate(delquery);
            
            JOptionPane.showMessageDialog(null,"Question is removed");
               }   
            if(course=="C#"){
            String delquery ="DELETE  FROM CSharp where ID ='"+i+"' ";
            st.executeUpdate(delquery);
            
            JOptionPane.showMessageDialog(null,"Question is removed");
               }    
            if(course=="PYTHON"){
            String delquery ="DELETE  FROM PYTHON where ID ='"+i+"' ";
            st.executeUpdate(delquery);
            
            JOptionPane.showMessageDialog(null,"Question is removed");
               }    
               }
             
               
               catch(Exception ae){
                   System.out.println(ae);
               }
               
                        i++;
                       view(i);
        // TODO add your handling code here:
    }//GEN-LAST:event_btndelActionPerformed

    private void btnbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbackActionPerformed
        dispose();
        new ManageCourse().setVisible(true);
    }//GEN-LAST:event_btnbackActionPerformed

    private void btnnextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnnextActionPerformed
                        i++;
                        if(i==11){
                            JOptionPane.showMessageDialog(null,"Question End");
                        }
                        view(i);        // TODO add your handling code here:
    }//GEN-LAST:event_btnnextActionPerformed

    private void btnprevActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnprevActionPerformed
        i--;
        view(i);
    }//GEN-LAST:event_btnprevActionPerformed

private void view(int j) {
        int ID=j;

            if(course=="C++"){
                
             query ="SELECT * FROM CPP where ID ='"+ID+"' ";
            viewQues();
             
            }
             if(course=="JAVA"){
                 
             query ="SELECT * FROM JAVA where ID ='"+ID+"' ";
        viewQues();
        
            }
             if(course=="C#"){
                 
             query ="SELECT * FROM CSharp where ID ='"+ID+"' ";
         viewQues();
         
            }
              if(course=="Python"){
                  
             query ="SELECT * FROM PYTHON where ID ='"+ID+"' ";
            viewQues();
            
                     }
               
    }

private void viewQues(){
    try{
         ResultSet rs = st.executeQuery(query);
         System.out.println("ok");
            while(rs.next())
            {
                String id =rs.getString("ID");
                NqID.setText(id);
              String Stmt = rs.getString("Q_Stmt");
              NqStatement.setText(Stmt);
                 String op1 = rs.getString("op_1");
                No1.setText(op1);
               
                  String op2 = rs.getString("op_2");
                                   No2.setText(op2);

                  String op3 = rs.getString("op_3");
                                   No3.setText(op3);

                  String op4 = rs.getString("op_4");
                                   No4.setText(op4);

                   String op5 = rs.getString("correct_op");
                                                      correctOption.setText(op5);      
            }
        
    }catch(Exception e){
        System.out.println(e);
    }
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField No1;
    private javax.swing.JTextField No2;
    private javax.swing.JTextField No3;
    private javax.swing.JTextField No4;
    private javax.swing.JTextField NqID;
    private javax.swing.JTextArea NqStatement;
    private javax.swing.JButton btnback;
    private java.awt.Button btndel;
    private java.awt.Button btnnext;
    private java.awt.Button btnprev;
    private javax.swing.JTextField correctOption;
    private javax.swing.JLabel cours;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
